// Types for postcode.js, so the React app in web/ can IMPORT the Malaysian postcode table rather than
// carry a second copy of it (see postcode.js's own header, and web/src/finance-info.tsx).
//
// Declarations only. This file must never grow a postcode, a locality or a state: postcode.js is the
// single copy, generated by tools/gen_postcodes.ts and pinned by tests/postcode_test.ts. A code typed
// in here would be a second answer that nothing checks — and the failure mode is a statutory address.
//
// It sits next to postcode.js, not inside web/, for the same reason wht.d.ts sits next to wht.js:
// `web/tsconfig.json` sets `allowJs: false` and TypeScript resolves a RELATIVE specifier on disk — an
// ambient wildcard module declaration does not apply to `../../postcode.js`.

/** What a postcode resolves to. `state` is one of MY_STATES; `cities` is Pos Malaysia's postal
 *  locality (or localities — a handful of codes serve more than one), sorted, never empty. */
export interface PostcodeHit {
  state: string;
  cities: string[];
}

/** `{ state, cities }` for a five-digit Malaysian postcode, or null — including for a PARTIAL one. */
export function myPostcodeFind(pc: unknown): PostcodeHit | null;

/** state -> locality -> space-separated postcodes. The table itself; prefer myPostcodeFind(). */
export const MY_POSTCODES: Record<string, Record<string, string>>;
