import type { ReactNode } from 'react';

// app.html's own stylesheet — Finance OS's, NOT HR OS's. Same arrangement as app/hr/layout.tsx and for
// the same reason: the two legacy apps disagree on 38 selectors including the whole `:root` token set,
// so they are scoped per route tree rather than concatenated. Generated by scripts/sync-legacy-css.mjs;
// never edited, never committed.
import './legacy.css';

export default function FinanceLayout({ children }: { children: ReactNode }) {
  return children;
}
