'use client';

// Finance OS's route tree: the stylesheet scoping, and the shell every Finance screen sits inside.
//
// app.html's own stylesheet — Finance OS's, NOT HR OS's. Same arrangement as app/hr/layout.tsx and for
// the same reason: the two legacy apps disagree on 38 selectors including the whole `:root` token set,
// so they are scoped per route tree rather than concatenated. Generated by scripts/sync-legacy-css.mjs;
// never edited, never committed.
import './legacy.css';
import '../../src/shell.css';

import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { usePathname } from 'next/navigation';

import ConfirmHost from '../../src/confirm';
import FinanceShell, { roleLabel, type Company } from '../../src/finance-shell';
import { financeCatsFor, financeNavFor, type Perms } from '../../src/nav';
import PasswordHost, { openPasswordModal } from '../../src/password-modal';
import { BASE_PATH, call, token } from '../../src/portal';
import { THEME_KEYS, asTheme } from '../../src/theme';
import ToastHost, { toast } from '../../src/toast';
import { useSpaNav } from '../../src/use-spa-nav';

const read = (k: string) => { try { return localStorage.getItem(k) || ''; } catch { return ''; } };

interface Me { user?: { name?: string; email?: string; role?: string; must_change_pw?: boolean }; companies?: Company[] }

export default function FinanceLayout({ children }: { children: ReactNode }) {
  // `/finance/wht/` → 'wht'. The route segment IS the tab's `data-t` — one string, no mapping table.
  const active = (usePathname() || '').split('/').filter(Boolean)[1] || '';

  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [me, setMe] = useState<Me | null>(null);
  const [perms, setPerms] = useState<Perms | null>(null);
  const [company, setCompany] = useState('');
  const [online, setOnline] = useState(true);
  const [theme, setTheme] = useState<'light' | 'dark'>('light');
  // `enterApp()` — app.html:2665. A temporary password must be replaced before the app is shown at all.
  const [mustChangePw, setMustChangePw] = useState(false);

  // Every anchor in this route tree that points at another Finance screen becomes a client-side route
  // change instead of a document load; see src/spa-nav.ts for the rule and why it stops at the boundary.
  useSpaNav();

  useEffect(() => {
    // app.html:1014 — the CTG brand default is light. The ATTRIBUTE is already correct by now:
    // app/layout.tsx runs src/theme.ts's blocking <head> script, which reads this same key before the
    // first paint, exactly as app.html:1012 does. This is React catching up with it, so the theme
    // button's glyph matches what is on screen.
    const t = asTheme(read(THEME_KEYS.finance));
    setTheme(t);
    document.documentElement.setAttribute('data-theme', t);

    // `updateConn()` — app.html:1340. The dot is the live connection state, not decoration.
    const sync = () => setOnline(navigator.onLine);
    sync();
    addEventListener('online', sync);
    addEventListener('offline', sync);

    const signed = !!token();
    setSignedIn(signed);
    if (signed) {
      // app.html:7698 — `me` returns the user AND the Xero orgs the top-bar picker is built from.
      void call<Me>({ api: 'me' }).then((m) => {
        setMe(m);
        // app.html:2665 — `enterApp()` hides `#app` and forces the dialog. Nothing else is rendered.
        if (m?.user?.must_change_pw) setMustChangePw(true);
      }).catch(() => setMe({}));
      // `showApp()` — app.html:1416. The permission set is what decides which of the 22 tabs exist.
      // No fallbackPerms() equivalent: the legacy one keeps a user from being locked out of a page they
      // are already inside, whereas here a failed call would ADVERTISE tabs, which is the wrong
      // direction to fail in. An unresolved permission set shows no tabs.
      void call<Perms>({ api: 'my_perms' }).then(setPerms).catch(() => setPerms(null));
    }
    return () => { removeEventListener('online', sync); removeEventListener('offline', sync); };
  }, []);

  /** `toggleTheme()` — app.html:1036. Same key, same two values. */
  const onToggleTheme = useCallback(() => {
    const next = document.documentElement.getAttribute('data-theme') === 'light' ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', next);
    setTheme(next);
    try { localStorage.setItem(THEME_KEYS.finance, next); } catch { /* private mode */ }
  }, []);

  /**
   * `onCompany()` — app.html:1526. The legacy one drops four caches and re-renders the active tab; here
   * each screen owns its own fetch, so a reload is the same thing with nothing left to forget. The
   * selection is deliberately NOT persisted, exactly as in app.html, where `curCo()` reads it straight
   * off the select and it resets to "— All Companies —" on every load.
   */
  const onPickCompany = useCallback((tid: string) => setCompany(tid), []);

  /** `reloadActive()` — app.html:1509. Nothing here holds the screen's data, so the screen reloads. */
  const onRefresh = useCallback(() => location.reload(), []);

  /** `logout()` — app.html:1394. Same key, same destination. */
  const onSignOut = useCallback(() => {
    try { localStorage.removeItem('ctg_portal_token'); } catch { /* private mode */ }
    location.href = `${BASE_PATH}/index.html`;
  }, []);

  /**
   * `doChangePw()` — app.html:2622. The POST and the toast; the dialog, its validation ladder and its
   * forced branch are src/password-modal.tsx.
   */
  const onSavePassword = useCallback(async (oldp: string, neu: string) => {
    await call({ api: 'changepw', old: oldp, neu });
    toast('✅ Password updated');
  }, []);

  // The three chrome hosts, outside every early return: see app/hr/layout.tsx for why a screen that is
  // not signed in still needs a toast, and why a `showConfirm()` with no host mounted resolves false.
  const hosts = (
    <>
      <ToastHost />
      <ConfirmHost />
      <PasswordHost onSave={onSavePassword} forcedOnMount={mustChangePw}
        onForcedDone={() => location.reload()} />
    </>
  );

  // app.html:2665 — the whole app is hidden until the temporary password is replaced.
  if (mustChangePw) return hosts;

  // Not signed in (or still finding out): NO chrome — the tab bar names every Finance screen and which
  // ones this login may reach. See app/hr/layout.tsx.
  if (!signedIn) return <><main style={{ padding: '28px 34px 64px' }}>{children}</main>{hosts}</>;

  return (
    <><FinanceShell
      active={active}
      tabs={financeNavFor(perms)}
      cats={financeCatsFor(perms)}
      who={me?.user?.name || me?.user?.email || ''}
      role={perms?.label || roleLabel(me?.user?.role)}
      companies={me?.companies || []}
      company={company}
      online={online}
      theme={theme}
      onPickCompany={onPickCompany}
      onToggleTheme={onToggleTheme}
      onRefresh={onRefresh}
      onChangePassword={() => openPasswordModal(false)}
      onSignOut={onSignOut}
    >{children}</FinanceShell>{hosts}</>
  );
}
