'use client';

// Finance OS's route tree: the stylesheet scoping, and the shell every Finance screen sits inside.
//
// app.html's own stylesheet — Finance OS's, NOT HR OS's. Same arrangement as app/hr/layout.tsx and for
// the same reason: the two legacy apps disagree on 38 selectors including the whole `:root` token set,
// so they are scoped per route tree rather than concatenated. Generated by scripts/sync-legacy-css.mjs;
// never edited, never committed.
import './legacy.css';
import '../../src/shell.css';

import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { usePathname } from 'next/navigation';

import ConfirmHost from '../../src/confirm';
import AlertsPanel, { alertFeeds, alertHref, alertsFor, badgeText, computeAlerts,
  type Alert, type OverviewLite, type PendingLite } from '../../src/finance-alerts';
import { NOTHING_TO_EXPORT, exportFileName, exportLogBody, screenExport, sheetName } from '../../src/finance-export';
import SecurityHost, { disableBody, openSecurityModal, verifyBody } from '../../src/finance-security';
import FinanceShell, { roleLabel, type Company } from '../../src/finance-shell';
import { financeCatsFor, financeNavFor, type Perms } from '../../src/nav';
import PasswordHost, { openPasswordModal } from '../../src/password-modal';
import { BASE_PATH, call, legacyUrl, token } from '../../src/portal';
import { THEME_KEYS, asTheme } from '../../src/theme';
import ToastHost, { toast } from '../../src/toast';
import { useSpaNav } from '../../src/use-spa-nav';

const read = (k: string) => { try { return localStorage.getItem(k) || ''; } catch { return ''; } };

interface Me { user?: { name?: string; email?: string; role?: string; must_change_pw?: boolean; totp_enabled?: boolean }; companies?: Company[] }

/** The vendored `xlsx.full.min.js`, injected on FIRST USE — app/finance/recon/page.tsx's arrangement.
    Nothing imports it: a 952 KB bundle on every Finance page load is the thing that must not happen. */
interface Xlsx { utils: { book_new(): unknown; table_to_sheet(t: Element): unknown; book_append_sheet(wb: unknown, ws: unknown, n: string): void }; writeFile(wb: unknown, fn: string): void }
let xlsxPromise: Promise<Xlsx | null> | null = null;
function loadXlsx(): Promise<Xlsx | null> {
  const w = window as unknown as { XLSX?: Xlsx };
  if (w.XLSX) return Promise.resolve(w.XLSX);
  if (!xlsxPromise) {
    xlsxPromise = new Promise<Xlsx | null>((res) => {
      const s = document.createElement('script');
      s.src = legacyUrl('xlsx.full.min.js');
      s.onload = () => res(w.XLSX || null);
      s.onerror = () => { xlsxPromise = null; res(null); };
      document.head.appendChild(s);
    });
  }
  return xlsxPromise;
}

export default function FinanceLayout({ children }: { children: ReactNode }) {
  // `/finance/wht/` → 'wht'. The route segment IS the tab's `data-t` — one string, no mapping table.
  const active = (usePathname() || '').split('/').filter(Boolean)[1] || '';

  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [me, setMe] = useState<Me | null>(null);
  const [perms, setPerms] = useState<Perms | null>(null);
  const [company, setCompany] = useState('');
  const [online, setOnline] = useState(true);
  const [theme, setTheme] = useState<'light' | 'dark'>('light');
  // `enterApp()` — app.html:2665. A temporary password must be replaced before the app is shown at all.
  const [mustChangePw, setMustChangePw] = useState(false);
  // `NOTIFS` + the panel's own open flag — app.html:2705, :2744.
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [alertsOpen, setAlertsOpen] = useState(false);
  // `ME.totp_enabled` — app.html:2541, kept in step by `onChanged` as app.html:2586/:2601 do.
  const [totp, setTotp] = useState(false);
  // `exportCurrent()` reads the ACTIVE tab's own panel div (app.html:5278). The shell owns the frame,
  // so the equivalent is the element the current screen renders into — NOT the document.
  const screen = useRef<HTMLDivElement | null>(null);

  // Every anchor in this route tree that points at another Finance screen becomes a client-side route
  // change instead of a document load; see src/spa-nav.ts for the rule and why it stops at the boundary.
  useSpaNav();

  /**
   * `loadNotifs()` — app.html:2722-2730.
   *
   * The two feeds are asked for only where the feature is granted, `Promise.allSettled` so one failure
   * does not empty the bell, and the produced alerts are filtered by that same feature list — see
   * src/finance-alerts.tsx for why that second pass is a boundary and not a tidy-up.
   */
  const loadAlerts = useCallback(async (pp: Perms | null) => {
    const feeds = alertFeeds(pp?.features);
    try {
      const settled = await Promise.allSettled(feeds.map((f) => call<Record<string, unknown>>({ api: f })));
      const got = (name: 'overview' | 'pending') => {
        const i = feeds.indexOf(name);
        return i >= 0 && settled[i].status === 'fulfilled' ? (settled[i] as PromiseFulfilledResult<unknown>).value : null;
      };
      setAlerts(alertsFor(computeAlerts(got('overview') as OverviewLite | null, got('pending') as PendingLite | null), pp?.features));
    } catch { setAlerts([]); }
  }, []);

  useEffect(() => {
    // app.html:1014 — the CTG brand default is light. The ATTRIBUTE is already correct by now:
    // app/layout.tsx runs src/theme.ts's blocking <head> script, which reads this same key before the
    // first paint, exactly as app.html:1012 does. This is React catching up with it, so the theme
    // button's glyph matches what is on screen.
    const t = asTheme(read(THEME_KEYS.finance));
    setTheme(t);
    document.documentElement.setAttribute('data-theme', t);

    // `updateConn()` — app.html:1340. The dot is the live connection state, not decoration.
    const sync = () => setOnline(navigator.onLine);
    sync();
    addEventListener('online', sync);
    addEventListener('offline', sync);

    const signed = !!token();
    setSignedIn(signed);
    if (signed) {
      // app.html:7698 — `me` returns the user AND the Xero orgs the top-bar picker is built from.
      void call<Me>({ api: 'me' }).then((m) => {
        setMe(m);
        // app.html:2665 — `enterApp()` hides `#app` and forces the dialog. Nothing else is rendered.
        if (m?.user?.must_change_pw) setMustChangePw(true);
        setTotp(!!m?.user?.totp_enabled);
      }).catch(() => setMe({}));
      // `showApp()` — app.html:1416. The permission set is what decides which of the 22 tabs exist.
      // No fallbackPerms() equivalent: the legacy one keeps a user from being locked out of a page they
      // are already inside, whereas here a failed call would ADVERTISE tabs, which is the wrong
      // direction to fail in. An unresolved permission set shows no tabs.
      void call<Perms>({ api: 'my_perms' }).then((pp) => { setPerms(pp); void loadAlerts(pp); }).catch(() => setPerms(null));
    }
    return () => { removeEventListener('online', sync); removeEventListener('offline', sync); };
  }, []);

  /**
   * The two ways the alert panel closes without a decision — app.html:2747-2756.
   *
   * A click that is neither the panel nor the bell, and Escape. Both are ported because the panel is
   * `position:fixed` over the screen: without them it stays over whatever the operator clicks next. The
   * bell's own handler calls `stopPropagation()` (src/finance-shell.tsx) so opening it does not
   * immediately close it again.
   */
  useEffect(() => {
    if (!alertsOpen) return;
    const away = (e: MouseEvent) => {
      const t = e.target as Node | null;
      const panel = document.getElementById('notif-panel');
      const bell = document.getElementById('notif-btn');
      if (panel && t && !panel.contains(t) && bell && !bell.contains(t)) setAlertsOpen(false);
    };
    const esc = (e: KeyboardEvent) => { if (e.key === 'Escape') setAlertsOpen(false); };
    document.addEventListener('click', away);
    document.addEventListener('keydown', esc);
    return () => { document.removeEventListener('click', away); document.removeEventListener('keydown', esc); };
  }, [alertsOpen]);

  /** `toggleTheme()` — app.html:1036. Same key, same two values. */
  const onToggleTheme = useCallback(() => {
    const next = document.documentElement.getAttribute('data-theme') === 'light' ? 'dark' : 'light';
    document.documentElement.setAttribute('data-theme', next);
    setTheme(next);
    try { localStorage.setItem(THEME_KEYS.finance, next); } catch { /* private mode */ }
  }, []);

  /**
   * `onCompany()` — app.html:1526. The legacy one drops four caches and re-renders the active tab; here
   * each screen owns its own fetch, so a reload is the same thing with nothing left to forget. The
   * selection is deliberately NOT persisted, exactly as in app.html, where `curCo()` reads it straight
   * off the select and it resets to "— All Companies —" on every load.
   */
  const onPickCompany = useCallback((tid: string) => setCompany(tid), []);

  /** `reloadActive()` — app.html:1509. Nothing here holds the screen's data, so the screen reloads. */
  const onRefresh = useCallback(() => location.reload(), []);

  /** `logout()` — app.html:1394. Same key, same destination. */
  const onSignOut = useCallback(() => {
    try { localStorage.removeItem('ctg_portal_token'); } catch { /* private mode */ }
    location.href = `${BASE_PATH}/index.html`;
  }, []);

  /**
   * `doChangePw()` — app.html:2622. The POST and the toast; the dialog, its validation ladder and its
   * forced branch are src/password-modal.tsx.
   */
  const onSavePassword = useCallback(async (oldp: string, neu: string) => {
    await call({ api: 'changepw', old: oldp, neu });
    toast('✅ Password updated');
  }, []);

  /**
   * `exportCurrent()` — app.html:5275-5302.
   *
   * The scrape, the workbook and the download; the naming and the audit body are src/finance-export.ts.
   * The P&L special case (app.html:5277) is a registration rather than a call by name, because the
   * chrome cannot reach a screen's model — see that file's header.
   */
  const onExport = useCallback(async () => {
    const own = screenExport();
    if (own) { own(); return; }
    const tables = screen.current ? Array.from(screen.current.querySelectorAll('table.bigtable')) : [];
    if (!tables.length) { toast(NOTHING_TO_EXPORT, true); return; }
    const XLSX = await loadXlsx();
    if (!XLSX) { toast('Could not load the spreadsheet engine (xlsx.full.min.js).', true); return; }
    const tab = active || 'overview';
    try {
      const wb = XLSX.utils.book_new();
      tables.forEach((tb, i) => XLSX.utils.book_append_sheet(wb, XLSX.utils.table_to_sheet(tb), sheetName(tab, i, tables.length)));
      const sel = document.getElementById('company') as HTMLSelectElement | null;
      const coText = sel && sel.selectedIndex >= 0 ? sel.options[sel.selectedIndex].text : '';
      const fn = exportFileName(tab, coText, new Date());
      XLSX.writeFile(wb, fn);
      toast('Exported ' + fn);
      // Fire-and-forget audit so admins can see who exported what — app.html:5295.
      const rows = tables.reduce((a, tb) => a + Math.max(0, tb.querySelectorAll('tbody tr').length), 0);
      void call(exportLogBody(tab, rows, fn)).catch(() => {});
    } catch (e) {
      toast('Export failed: ' + (e instanceof Error && e.message ? e.message : String(e)), true);
    }
  }, [active]);

  // The chrome hosts, outside every early return: see app/hr/layout.tsx for why a screen that is
  // not signed in still needs a toast, and why a `showConfirm()` with no host mounted resolves false.
  const hosts = (
    <>
      <ToastHost />
      <ConfirmHost />
      <PasswordHost onSave={onSavePassword} forcedOnMount={mustChangePw}
        onForcedDone={() => location.reload()} />
      {/* `{api:'totp_*'}` — app.html:2559/:2588/:2600. The dialog and its three steps are
          src/finance-security.tsx; the network and the two toasts (app.html:2589, :2601) are here. */}
      <SecurityHost enabled={totp}
        onSetup={() => call<{ secret: string; otpauth_url: string }>({ api: 'totp_setup' })}
        onVerify={async (code) => { await call(verifyBody(code)); }}
        onDisable={async (pw) => { await call(disableBody(pw)); }}
        onChanged={(on) => { setTotp(on); toast(on ? '✅ Two-factor authentication enabled' : 'Two-factor disabled'); }} />
    </>
  );

  // app.html:2665 — the whole app is hidden until the temporary password is replaced.
  if (mustChangePw) return hosts;

  // Not signed in (or still finding out): NO chrome — the tab bar names every Finance screen and which
  // ones this login may reach. See app/hr/layout.tsx.
  if (!signedIn) return <><main style={{ padding: '28px 34px 64px' }}>{children}</main>{hosts}</>;

  const tabs = financeNavFor(perms);
  return (
    <><FinanceShell
      active={active}
      tabs={tabs}
      cats={financeCatsFor(perms)}
      who={me?.user?.name || me?.user?.email || ''}
      role={perms?.label || roleLabel(me?.user?.role)}
      companies={me?.companies || []}
      company={company}
      online={online}
      theme={theme}
      onPickCompany={onPickCompany}
      onToggleTheme={onToggleTheme}
      onRefresh={onRefresh}
      onChangePassword={() => openPasswordModal(false)}
      onToggleAlerts={() => { if (!alertsOpen) void loadAlerts(perms); setAlertsOpen((o) => !o); }}
      alertBadge={badgeText(alerts.length)}
      onSecurity={() => openSecurityModal()}
      onExport={onExport}
      onSignOut={onSignOut}
    ><div ref={screen}>{children}</div></FinanceShell>
    {/* app.html:1185 — the panel sits OUTSIDE `#app`, which is what `position:fixed` (app.html:253)
        expects. `notifGo()` closes it and then opens the alert's own tab (app.html:2746). */}
    <AlertsPanel open={alertsOpen} alerts={alerts} tabs={tabs}
      onRefresh={() => { void loadAlerts(perms); }}
      onGo={(i) => {
        setAlertsOpen(false);
        const h = alertHref(tabs, alerts[i]?.tab || '');
        if (h) location.href = h;
      }} />
    {hosts}</>
  );
}
